### ISSUE TITLE
Add wait/retry loop for CLI's 

### ISSUE THREAD

**Issue by lockefox** [j9ac9k/NavitronEve#1]
Wrap the `run_main()` section with some [retry](https://pypi.python.org/pypi/retry/) library.  Probably want to set timeout in minutes, not seconds

**Comment by lockefox** [comment]
server status call at downtime

[ERROR:navitron_server_status.py--main:71]
navitron_server_status: Unable to fetch server_info
```python
Traceback (most recent call last):
  File "/home/lockefox/NavitronEve/crons/navitron_crons/navitron_server_status.py", line 65, in main
    logger=self.logger
  File "/home/lockefox/NavitronEve/crons/navitron_crons/navitron_server_status.py", line 36, in get_server_status
    logger=logger
  File "/home/lockefox/NavitronEve/crons/navitron_crons/connections.py", line 45, in get_esi
    req.raise_for_status()
  File "/home/lockefox/.virtualenvs/navitron_cron_venv/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://esi.tech.ccp.is/latest/status/
```

**Comment by lockefox** [comment]
system info call during ESI update

[ERROR:navitron_system_stats.py--main:116]
navitron_system_stats: Unable to fetch system_kills
```python
Traceback (most recent call last):
  File "/home/lockefox/NavitronEve/crons/navitron_crons/navitron_system_stats.py", line 110, in main
    logger=self.logger
  File "/home/lockefox/NavitronEve/crons/navitron_crons/navitron_system_stats.py", line 63, in get_system_kills
    logger=logger
  File "/home/lockefox/NavitronEve/crons/navitron_crons/connections.py", line 45, in get_esi
    req.raise_for_status()
  File "/home/lockefox/.virtualenvs/navitron_cron_venv/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://esi.tech.ccp.is/latest/universe/system_kills/
```
